on:
  workflow_dispatch:
    inputs:
      buildType:
        description: "æ„å»ºç±»å‹"
        required: true
        default: "prod-v8a"
        type: choice
        options:
          - prod-v8a
          - prod-universal
          - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ— Setup repo
        uses: actions/checkout@v3

      - name: ğŸ¤– Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: ğŸ— Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: pnpm

      - name: ğŸ— Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          packager: pnpm

      - name: ğŸ“¦ Install dependencies
        run: pnpm install

      - name: ğŸš€ Build ${{ github.event.inputs.buildType }} APK
        run: SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }} eas build --platform android --profile ${{ github.event.inputs.buildType }} --local --no-wait --output=${{runner.temp}}/app.apk

      - name: ğŸš€ Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: bbplayer-${{ github.event.inputs.buildType }}.apk
          path: ${{runner.temp}}/app.apk
          if-no-files-found: error

      - name: ğŸš€ Bump version number
        uses: EndBug/add-and-commit@v9
        if: github.event.inputs.buildType == 'prod-v8a' || github.event.inputs.buildType == 'prod-universal'
        with:
          # æ›´æ–°åº”ç”¨ç‰ˆæœ¬å·
          message: "chore: bump version number"
          committer_name: GitHub Actions
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com

      - name: ğŸ Draft release
        if: github.event.inputs.buildType == 'prod-v8a' || github.event.inputs.buildType == 'prod-universal'
        env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            gh release create "v$(node -p "require('./package.json').version")" '${{runner.temp}}/app.apk#bbplayer-v$(node -p "require('./package.json').version")-${{ github.event.inputs.buildType }}.apk' --title "v$(node -p "require('./package.json').version")" --draft --notes "auto release by GitHub Actions"
