name: Build and Release

on:
  workflow_dispatch:
    inputs:
      buildType:
        description: 'ÊûÑÂª∫Á±ªÂûã'
        required: true
        default: 'prod-universal'
        type: choice
        options:
          - prod-v8a
          - dev
          - blank-test

env:
  NODE_VERSION: 22.x
  PNPM_VERSION: 10
  EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: üèó Setup repo
        uses: actions/checkout@v3

      - name: ü§ñ Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: üèó Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm

      - name: üèó Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ env.EXPO_TOKEN }}
          packager: pnpm

      - name: üì¶ Install dependencies
        run: pnpm install

      - name: ‚öôÔ∏è Prepare Variables
        id: prep
        run: |
          APP_VERSION=$(node -p "require('./package.json').version")

          APK_NAME="bbplayer-v${APP_VERSION}-${{ github.event.inputs.buildType }}.zip"
          RELEASE_TAG="v${APP_VERSION}"

          echo "APP_VERSION=${APP_VERSION}" >> $GITHUB_ENV
          echo "APK_NAME=${APK_NAME}" >> $GITHUB_ENV
          echo "RELEASE_TAG=${RELEASE_TAG}" >> $GITHUB_ENV
          echo "APK_TEMP_PATH=${{runner.temp}}/app.apk" >> $GITHUB_ENV

      - name: üöÄ Build ${{ github.event.inputs.buildType }} APK
        if: github.event.inputs.buildType != 'blank-test'
        run: eas build --platform android --profile ${{ github.event.inputs.buildType }} --local --no-wait --output=${{ env.APK_TEMP_PATH }}

      - name: üß™ Create Dummy APK for Blank Test
        if: github.event.inputs.buildType == 'blank-test'
        run: |
          echo "This is a dummy APK for testing workflow. BuildType: ${{ github.event.inputs.buildType }}" > ${{ env.APK_TEMP_PATH }}
          echo "Created a dummy file at ${{ env.APK_TEMP_PATH }}"

      - name: üöÄ Upload APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APK_NAME }}
          path: ${{ env.APK_TEMP_PATH }}
          if-no-files-found: error

      - name: üéÅ Draft Release
        if: startsWith(github.event.inputs.buildType, 'prod') || github.event.inputs.buildType == 'blank-test'
        run: |
          gh release create ${{ env.RELEASE_TAG }} \
            "${{ env.APK_TEMP_PATH }}#${{ env.APK_NAME }}" \
            --title "${{ env.RELEASE_TAG }}" \
            --draft \
            --notes "auto release by GitHub Actions"
